### ISSUE TITLE
TC7 depends on hiworkload 

### ISSUE THREAD

**Issue by lpechacek** [lpechacek/qa_test_klp#2]
hiworkload has unknown origin and its function needs to be reviewed. Possibly the part depending on hiworkload can be dropped.

**Comment by pevik** [comment]
@mimi1vx Any comments?

**Comment by mimi1vx** [comment]
@pevik -1 dependency has +1 fro me :D

**Comment by wang0z** [comment]
> hiworkload has unknown origin and its function needs to be reviewed. Possibly the part depending on hiworkload can be dropped.

 I wrote it from the scratch.  So IBS is actually the original place.
And chi in chimem is a chinese pinyin meaning 'eat'.

**Comment by pevik** [comment]
Do we want to add `hiworkload` source code or just a check if it's available (and skip tests which require it?). And if we add it, what is the license? GPL v2+ ?

**Comment by lpechacek** [comment]
@pevik, sorry for the long silence here. Now that I see the pull request in place, let's not change the direction and include `chimem` in the sources.
@wang0z, please confirm GPL v2+ license for `chimem` or propose a new one. I'll review and merge the pull request then.

Thanks!

**Comment by pevik** [comment]
@wang0z ping, please.

**Comment by lpechacek** [comment]
Lance is now working for a famous Chinese technology company and maybe is no longer involved in FOSS development. Let's assume at this point that his work for SUSE is licensed under GPL-2.0.

**Comment by wang0z** [comment]
> Lance is now working for a famous Chinese technology company and maybe is no longer involved in FOSS development. Let's assume at this point that his work for SUSE is licensed under GPL-2.0.

Better late than never. Absolutely Yes, it is licensed under GPL-2.0.
